language: objective-c
osx_image: xcode9.2
gemfile: Gemfile

cache:
  - cocoapods
  - bundler

script:
   - xcodebuild analyze test -workspace YPNavigationBarTransition.xcworkspace -scheme YPNavigationBarTransitionLibrary -sdk iphonesimulator -destination "OS=11.2,name=iPhone 8" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=YES | bundle exec xcpretty -c
   - xcodebuild build -workspace YPNavigationBarTransition.xcworkspace -scheme YPNavigationBarTransition-Example -sdk iphonesimulator -destination "OS=11.2,name=iPhone 8" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | bundle exec xcpretty -c

after_success:
  - bundle exec slather