# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

target "RainForestSwift" do
  pod "AsyncDisplayKit", git: "git@github.com:facebook/AsyncDisplayKit.git", tag: "2.0-beta.1"
end
