module: XRouter
author: Reece Como
readme: README.md
author_url: https://github.com/reececomo/
github_url: https://github.com/reececomo/XRouter.git
copyright: 'MIT License'

clean: true
skip_undocumented: false
hide_documentation_coverage: false
output: docs
theme: apple
undocumented_text: 'Undocumented'
xcodebuild_arguments:
  - -workspace
  - 'Example/XRouter.xcworkspace'
  - -scheme
  - 'XRouter'
  - -sdk
  - 'iphonesimulator12.1'
  - -UseModernBuildSystem=NO