osx_image: xcode10.1
language: swift

# Build with tests
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/XRouter.xcworkspace -scheme XRouter-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE,OS=12.1' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

# Upload test coverage results to CodeCov
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'XRouter' -X fix