language: swift
branches:
  only:
    - master
    - next
cache:
  directories:
  - /usr/local/Homebrew
  - $HOME/Library/Caches/Homebrew
before_cache:
  - brew cleanup
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
skip_cleanup: true
jobs:
  include:
  - stage: Build framework(swift 4.1)
    osx_image: xcode9.4
    script:
    - xcodebuild -scheme FloatingPanel clean build

  - stage: Build framework(swift 4.2)
    osx_image: xcode10
    script:
    - xcodebuild -scheme FloatingPanel clean build

  - stage: Carthage
    osx_image: xcode10
    before_install:
    - brew update
    - brew outdated carthage || brew upgrade carthage
    script:
    - carthage build --no-skip-current

  - stage: Podspec
    osx_image: xcode10
    script:
    - pod spec lint

  - stage: Build maps example
    osx_image: xcode10
    script:
    - xcodebuild -scheme Maps -sdk iphonesimulator clean build

  - stage: Build stocks example
    osx_image: xcode10
    script:
    - xcodebuild -scheme Stocks -sdk iphonesimulator clean build

  - stage: Build samples example
    osx_image: xcode10
    script:
    - xcodebuild -scheme Samples -sdk iphonesimulator clean build
